# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html
from sys import stderr

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'Introduction to Programming with Python'
copyright = '2025, TODO'
author = 'TODO'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = []

templates_path = ['_templates']
exclude_patterns = []

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
# https://www.sphinx-doc.org/en/master/usage/advanced/intl.html
language = 'en'
locale_dirs = ["locale/"]


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'alabaster'
html_static_path = ['_static']



# own directive
from docutils.parsers import rst
from docutils import nodes
from email.utils import parseaddr
import glob
import subprocess
import unicodedata

PO_PATH = 'source/locale/%s/LC_MESSAGES/*.po'

class Contributors(rst.Directive):
    _GIT_COMMAND = "git log --format=%aN"
    def run(self):
        try:
            return self.collect_authors_from_git()
        except (AttributeError, OSError, subprocess.CalledProcessError) as e:
            print("Project is not in a git repo", file=stderr)
            return []

    def collect_authors_from_git(self) -> []:
        """
        @throws CalledProcessError, OSError
        :return: set of author
        """
        authors = set(subprocess.check_output(self._GIT_COMMAND.split())
                      .splitlines())
        authors = set(map(lambda _a: unicodedata.normalize('NFC', _a.decode('utf-8')), authors))
        lang = self.state.document.settings.env.config.language
        for fname in glob.iglob(PO_PATH % lang):
            with open(fname) as po:
                lines = iter(po)
                for line in lines:
                    if line == "# Translators:\n":
                        break
                for line in lines:
                    if not line.startswith("# "):
                        break
                    translator = parseaddr(line[2:])[0]
                    authors.add(translator)

        bullet_list = nodes.bullet_list()
        for author in sorted(authors, key=str.lower):
            bullet_list.append(nodes.list_item(author,
                                               nodes.paragraph(author, author)))
        return [bullet_list]


def setup(app):
    app.add_directive('contributors', Contributors)
